# Generated by Django 4.1.7 on 2023-04-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='toibos',
            new_name='ToybossKg',
        ),
    ]
