# Generated by Django 4.1.7 on 2023-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название автомобиля')),
                ('description', models.TextField(verbose_name='Марка автомобиля')),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField()),
                ('cost', models.PositiveIntegerField()),
                ('video', models.URLField()),
                ('type_of_fuel', models.CharField(max_length=100, null=True)),
                ('steering_wheel', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('transmission_box', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
