# Generated by Django 4.1.7 on 2023-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Для  молодых парней', ' Для молодых парней'), ('Для мужчин', 'Для мужчин'), ('Для молодых девушек', 'Для молодых девушек '), ('Для женщин', 'Для женщин'), ('Для богатых', 'Для богатых')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Обзор на машину'),
        ),
    ]
